#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

rm -rf slurm* 0 constant/polyMesh log.* *log Sphere*> /dev/null 2>&1
rm -rf constant/extendedFeatureEdgeMesh constant/triSurface/*.eMesh


cleanCase

# ----------------------------------------------------------------- end-of-file
